export default function palavrasAndCategory() {
  return [
      { nome: "IRLANDA", categoria: "PAÍS" },
      { nome: "EQUADOR", categoria: "PAÍS" },
      { nome: "CHILE", categoria: "PAÍS" },
      { nome: "INDONESIA", categoria: "PAÍS" },
      { nome: "MALDIVAS", categoria: "LUGARES" },
      { nome: "INGLATERRA", categoria: "PAÍS" },
      { nome: "GROELANDIA", categoria: "PAÍS" },
      { nome: "UZBEQUISTAO", categoria: "PAÍS" },
      { nome: "CREGUENHEM", categoria: "LUGARES" },
      { nome: "BICICLETA", categoria: "TRANSPORTE" },
      { nome: "LANCHA", categoria: "TRANSPORTE" },
      { nome: "NAVIO", categoria: "TRANSPORTE" },
      { nome: "TELEFERICO", categoria: "TRANSPORTE" },
      { nome: "MOTOCICLETA", categoria: "TRANSPORTE" },
      { nome: "BARCO", categoria: "TRANSPORTE" },
      { nome: "AERONAVE", categoria: "TRANSPORTE" },
      { nome: "TREM", categoria: "TRANSPORTE" },
      { nome: "CAIAQUE", categoria: "TRANSPORTE" },
      { nome: "FUNICULAR", categoria: "TRANSPORTE" },
      { nome: "XICARA", categoria: "OBJETOS" },
      { nome: "MOEDA", categoria: "OBJETOS" },
      { nome: "ESPARADRAPO", categoria: "OBJETOS" },
      { nome: "SINO", categoria: "OBJETOS" },
      { nome: "CHUVEIRO", categoria: "OBJETOS" },
      { nome: "TAMBORETE", categoria: "OBJETOS" },
      { nome: "LAMPADA", categoria: "OBJETOS" },
      { nome: "BOCAL", categoria: "OBJETOS" },
      { nome: "CORTINA", categoria: "OBJETOS" },
      { nome: "LAPIS", categoria: "OBJETOS" },
      { nome: "MELANCIA", categoria: "ALIMENTOS" },
      { nome: "AMENDOIM", categoria: "ALIMENTOS" },
      { nome: "ESFIRRA", categoria: "ALIMENTOS" },
      { nome: "GOROROBA", categoria: "ALIMENTOS" },
      { nome: "JANTAR", categoria: "ALIMENTOS" },
      { nome: "SABOROSO", categoria: "ALIMENTOS" },
      { nome: "DESJEJUM", categoria: "ALIMENTOS" },
      { nome: "MASTIGAR", categoria: "ALIMENTOS" },
      { nome: "ENGOLIR", categoria: "ALIMENTOS" },
      { nome: "DOCERIA", categoria: "ALIMENTOS" },
      { nome: "DRAGAO", categoria: "ANIMAIS" },
      { nome: "GALINHA", categoria: "ANIMAIS" },
      { nome: "PAVAO", categoria: "ANIMAIS" },
      { nome: "CAMELO", categoria: "ANIMAIS" },
      { nome: "PERU", categoria: "ANIMAIS" },
      { nome: "ZEBRA", categoria: "ANIMAIS" },
      { nome: "DROMEDARIO", categoria: "ANIMAIS" },
      { nome: "CALANGO", categoria: "ANIMAIS" },
      { nome: "SAGUI", categoria: "ANIMAIS" },
      { nome: "LAGARTIXA", categoria: "ANIMAIS" },
      { nome: "HIPOPOTAMO", categoria: "ANIMAIS" },
      { nome: "A ERA DO GELO", categoria: "TV E CINEMA" },
      { nome: "HOMEM ARANHA", categoria: "TV E CINEMA" },
      { nome: "CASA MONSTRO", categoria: "TV E CINEMA" },
      { nome: "TELA QUENTE", categoria: "TV E CINEMA" },
      { nome: "STRANGER THINGS", categoria: "TV E CINEMA" },
      { nome: "O REI DO GADO", categoria: "TV E CINEMA" },
      { nome: "MULHER MARAVILHA", categoria: "TV E CINEMA" },
      { nome: "O INCRIVEL HULK", categoria: "TV E CINEMA" },
      { nome: "BOB ESPONJA", categoria: "TV E CINEMA" },
      { nome: "PANICO NA TV", categoria: "TV E CINEMA" },
      { nome: "SAMURAI", categoria: "CULTURA" },
      { nome: "KIMONO", categoria: "CULTURA" },
      { nome: "FESTIVAL", categoria: "CULTURA" },
      { nome: "TEMPLARIA", categoria: "HISTÓRIA" },
      { nome: "ROMA ANTIGA", categoria: "HISTÓRIA" },
      { nome: "CATEDRAL", categoria: "RELIGIÃO" },
      { nome: "SUTRA", categoria: "RELIGIÃO" },
      { nome: "SANTO", categoria: "RELIGIÃO" },
      { nome: "GUERREIRO", categoria: "MITOLOGIA" },
      { nome: "VALHALA", categoria: "MITOLOGIA" },
      { nome: "OLIMPO", categoria: "MITOLOGIA" },
      { nome: "ELECTRA", categoria: "MITOLOGIA" },
      { nome: "TRIDENTE", categoria: "OBJETOS" },
      { nome: "ENGRENAGEM", categoria: "OBJETOS" },
      { nome: "ENCICLOPEDIA", categoria: "OBJETOS" },
      { nome: "CALCULADORA", categoria: "OBJETOS" },
      { nome: "GRAMPO", categoria: "OBJETOS" },
      { nome: "QUADRO", categoria: "OBJETOS" },
      { nome: "TAÇA", categoria: "OBJETOS" },
      { nome: "CIMENTO", categoria: "MATERIAIS" },
      { nome: "CERAMICA", categoria: "MATERIAIS" },
      { nome: "CONCRETO", categoria: "MATERIAIS" },
      { nome: "TITANIO", categoria: "MATERIAIS" },
      { nome: "ACRILICO", categoria: "MATERIAIS" },
      { nome: "BONSAI", categoria: "NATUREZA" },
      { nome: "LAGO", categoria: "NATUREZA" },
      { nome: "ORQUIDEA", categoria: "NATUREZA" },
      { nome: "PANTANO", categoria: "NATUREZA" },
      { nome: "NEVASCA", categoria: "CLIMA" },
      { nome: "TORNADO", categoria: "CLIMA" },
      { nome: "ENCHENTE", categoria: "CLIMA" },
      { nome: "CICLONE", categoria: "CLIMA" },
      { nome: "TERREMOTO", categoria: "CLIMA" }
  ];
}